// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $analyze from "./routes/analyze.tsx";
import * as $api_path_ from "./routes/api/[...path].ts";
import * as $index from "./routes/index.tsx";
import * as $AnalysisContainer from "./islands/AnalysisContainer.tsx";
import * as $AnalysisForm from "./islands/AnalysisForm.tsx";
import * as $AnalysisResult from "./islands/AnalysisResult.tsx";
import * as $CustomQuery from "./islands/CustomQuery.tsx";
import * as $FileUpload from "./islands/FileUpload.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/analyze.tsx": $analyze,
    "./routes/api/[...path].ts": $api_path_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AnalysisContainer.tsx": $AnalysisContainer,
    "./islands/AnalysisForm.tsx": $AnalysisForm,
    "./islands/AnalysisResult.tsx": $AnalysisResult,
    "./islands/CustomQuery.tsx": $CustomQuery,
    "./islands/FileUpload.tsx": $FileUpload,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
