[project]
name = "quackview"
version = "0.1.0"
description = "Click & Analyze."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.3.2",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
]
